remote_theme: pages-themes/cayman@v0.2.0
title: "How the complexity of recipes and their nutritional characteristics influence user ratings"
description: ""
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one